// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using qDshunUtilities.EF;

#nullable disable

namespace qDshunUtilities.EF.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250418194639_AddedTimestampAttributeToChatLine")]
    partial class AddedTimestampAttributeToChatLine
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("qDshunUtilities.EF.Entities.ChatLineEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("WorldUserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("createdAt")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime(6)");

                    b.Property<string>("lineText")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("WorldUserId");

                    b.ToTable("ChatLines");
                });

            modelBuilder.Entity("qDshunUtilities.EF.Entities.LootItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<double>("Cost")
                        .HasColumnType("double");

                    b.Property<string>("CountExpression")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("LootSourceId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Rarity")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("LootSourceId");

                    b.ToTable("LootItems");
                });

            modelBuilder.Entity("qDshunUtilities.EF.Entities.LootSourceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("WorldId");

                    b.ToTable("LootSources");
                });

            modelBuilder.Entity("qDshunUtilities.EF.Entities.ObjectFieldEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("WorldObjectId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("WorldObjectId");

                    b.ToTable("ObjectFields");
                });

            modelBuilder.Entity("qDshunUtilities.EF.Entities.PermissionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("qDshunUtilities.EF.Entities.TemplateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("HTMLTemplate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("qDshunUtilities.EF.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("qDshunUtilities.EF.Entities.WorldEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Worlds");
                });

            modelBuilder.Entity("qDshunUtilities.EF.Entities.WorldObjectEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.HasIndex("WorldId");

                    b.ToTable("WorldObjects");
                });

            modelBuilder.Entity("qDshunUtilities.EF.Entities.WorldObjectPermissionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("WorldObjectId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("WorldUserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("WorldObjectId");

                    b.HasIndex("WorldUserId");

                    b.ToTable("WorldObjectPermissions");
                });

            modelBuilder.Entity("qDshunUtilities.EF.Entities.WorldUserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WorldId");

                    b.ToTable("WorldUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("qDshunUtilities.EF.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("qDshunUtilities.EF.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("qDshunUtilities.EF.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("qDshunUtilities.EF.Entities.ChatLineEntity", b =>
                {
                    b.HasOne("qDshunUtilities.EF.Entities.WorldUserEntity", "WorldUser")
                        .WithMany()
                        .HasForeignKey("WorldUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorldUser");
                });

            modelBuilder.Entity("qDshunUtilities.EF.Entities.LootItemEntity", b =>
                {
                    b.HasOne("qDshunUtilities.EF.Entities.LootSourceEntity", "LootSource")
                        .WithMany("LootItems")
                        .HasForeignKey("LootSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LootSource");
                });

            modelBuilder.Entity("qDshunUtilities.EF.Entities.LootSourceEntity", b =>
                {
                    b.HasOne("qDshunUtilities.EF.Entities.WorldEntity", "World")
                        .WithMany("LootSources")
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("World");
                });

            modelBuilder.Entity("qDshunUtilities.EF.Entities.ObjectFieldEntity", b =>
                {
                    b.HasOne("qDshunUtilities.EF.Entities.WorldObjectEntity", "WorldObject")
                        .WithMany("ObjectFields")
                        .HasForeignKey("WorldObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorldObject");
                });

            modelBuilder.Entity("qDshunUtilities.EF.Entities.WorldObjectEntity", b =>
                {
                    b.HasOne("qDshunUtilities.EF.Entities.TemplateEntity", "Template")
                        .WithMany("WorldObjects")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("qDshunUtilities.EF.Entities.WorldEntity", "World")
                        .WithMany("WorldObjects")
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");

                    b.Navigation("World");
                });

            modelBuilder.Entity("qDshunUtilities.EF.Entities.WorldObjectPermissionEntity", b =>
                {
                    b.HasOne("qDshunUtilities.EF.Entities.PermissionEntity", "Permission")
                        .WithMany("WorldObjectPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("qDshunUtilities.EF.Entities.WorldObjectEntity", "WorldObject")
                        .WithMany("WorldObjectPermissions")
                        .HasForeignKey("WorldObjectId");

                    b.HasOne("qDshunUtilities.EF.Entities.WorldUserEntity", "WorldUser")
                        .WithMany("WorldObjectPermissions")
                        .HasForeignKey("WorldUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("WorldObject");

                    b.Navigation("WorldUser");
                });

            modelBuilder.Entity("qDshunUtilities.EF.Entities.WorldUserEntity", b =>
                {
                    b.HasOne("qDshunUtilities.EF.Entities.UserEntity", "User")
                        .WithMany("WorldUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("qDshunUtilities.EF.Entities.WorldEntity", "World")
                        .WithMany("WorldUsers")
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("World");
                });

            modelBuilder.Entity("qDshunUtilities.EF.Entities.LootSourceEntity", b =>
                {
                    b.Navigation("LootItems");
                });

            modelBuilder.Entity("qDshunUtilities.EF.Entities.PermissionEntity", b =>
                {
                    b.Navigation("WorldObjectPermissions");
                });

            modelBuilder.Entity("qDshunUtilities.EF.Entities.TemplateEntity", b =>
                {
                    b.Navigation("WorldObjects");
                });

            modelBuilder.Entity("qDshunUtilities.EF.Entities.UserEntity", b =>
                {
                    b.Navigation("WorldUsers");
                });

            modelBuilder.Entity("qDshunUtilities.EF.Entities.WorldEntity", b =>
                {
                    b.Navigation("LootSources");

                    b.Navigation("WorldObjects");

                    b.Navigation("WorldUsers");
                });

            modelBuilder.Entity("qDshunUtilities.EF.Entities.WorldObjectEntity", b =>
                {
                    b.Navigation("ObjectFields");

                    b.Navigation("WorldObjectPermissions");
                });

            modelBuilder.Entity("qDshunUtilities.EF.Entities.WorldUserEntity", b =>
                {
                    b.Navigation("WorldObjectPermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
